name: Flutter Workflow

on: push
jobs:
  build:
    name: Build Flutter app
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable # or: beta, master (or main)
      - run: flutter --version

      - run: flutter pub get
      - run: flutter build apk --no-tree-shake-icons
      - run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-release-universal.apk

      - run: flutter build apk --no-tree-shake-icons --target-platform android-arm64 --release
      - run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-release-arm64.apk

      - run: flutter build appbundle --no-tree-shake-icons

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter build linux

      - run: tar -czvf release_linux.tar.gz build/linux/x64/release/bundle


      # - run: flutter build linux --no-tree-shake-icons

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: TODO New Release.
          draft: false
          prerelease: true
          files: |
            build/app/outputs/flutter-apk/app-release-universal.apk
            build/app/outputs/flutter-apk/app-release-arm64.apk
            build/app/outputs/bundle/release/app-release.aab
            release_linux.tar.gz
            