name: Flutter Workflow

on: push
jobs:
  build:
    name: Build Flutter app
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable # or: beta, master (or main)
      - run: flutter --version

      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle