name: Flutter Workflow

on: push
jobs:
  # build-linux:
  #   name: Build Flutter Linux Android App
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable # or: beta, master (or main)
  #         cache: true
  #     - run: flutter --version

  #     - run: flutter pub get
  #     - run: flutter build apk --no-tree-shake-icons
  #     - run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-release-universal.apk

  #     - run: flutter build apk --no-tree-shake-icons --target-platform android-arm64 --release
  #     - run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-release-arm64.apk

  #     - run: flutter build appbundle --no-tree-shake-icons

  #     - run: |
  #         sudo apt-get update -y
  #         sudo apt-get install -y ninja-build libgtk-3-dev
  #     - run: flutter build linux
  #     - run: tar -czvf release_linux.tar.gz build/linux/x64/release/bundle

  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: release_apk_universal
  #         path: build/app/outputs/flutter-apk/app-release-universal.apk

  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: release_apk_arm64
  #         path: build/app/outputs/flutter-apk/app-release-arm64.apk

  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: release_app
  #         path: build/app/outputs/bundle/release/app-release.aab

  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: release_linux
  #         path: release_linux.tar.gz


  # build-windows:
  #   name: Build Flutter Windows app
  #   runs-on: windows-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #         cache: true
  #     - run: flutter build windows

  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: release_exe
  #         path: build/windows/x64/runner/Release/rvc_client.exe

  release:
    name: Release
    runs-on: ubuntu-latest
    # needs: [build-linux, build-windows]
    steps:
      - name: Download release_apk_universal
        uses: actions/download-artifact@v4
        with:
          name: release_apk_universal

      - name: Download release_apk_arm64
        uses: actions/download-artifact@v4
        with:
          name: release_apk_arm64

      - name: Download release_app
        uses: actions/download-artifact@v4
        with:
          name: release_app

      - name: Download release_linux
        uses: actions/download-artifact@v4
        with:
          name: release_linux

      - name: Download release_exe
        uses: actions/download-artifact@v4
        with:
          name: release_exe

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: TODO New Release.
          draft: false
          prerelease: true
          files: |
            app-release-universal.apk
            app-release-arm64.apk
            app-release.aab
            release_linux.tar.gz
            