name: Build flutter app
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Build Android bundle
        uses: AcmeSoftwareLLC/flutter-build@v1
        with:
          platform: android
          build-name: 1.0.0
          build-number: 20231005
          # dart-define-file: configs/.env.production
          pub-get: true
          gen-icons: false